config/routes.rb
Rails.application.routes.draw do
  root to: 'communities#index'
  resources :comments
  resources :blogs
  resources :communities
  #devise_for :users do
  #	get '/users/sign_out' => 'devise/sessions#destroy'
  #end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	belongs_to :community

	validates :user, :community, :title, :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :blog

	validates :user, :blog, :body, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
	belongs_to :user

	validates :user, :title, :body, :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @comments = Comment.where(blog_id: params[:id]).order(created_at: :desc)
    @comment = Comment.new
    @comment.blog_id = @blog.id
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
    @blog.community_id = params[:community_id]
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :user_id, :community_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.js {}
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @blog = Blog.where(id: @comment.blog_id).first
    @comment.destroy
    respond_to do |format|
      #format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      #format.json { head :no_content }
      format.html { redirect_to @blog, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :blog_id)
    end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @communities = Community.all
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    @blogs = Blog.where(community_id: params[:id])
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)
    @community.user_id = current_user.id

    respond_to do |format|
      if @community.save
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params) and @community.user_id == current_user.id
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:title, :body, :url, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <%= f.hidden_field :community_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table class="table table-striped">

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td>
          <h3><%= link_to blog.title, blog_path(blog), :class=>"" %></h3>
          <% if signed_in? and current_user.id == blog.user_id %>
            <%= link_to 'Edit', edit_blog_path(blog), :class=>"btn btn-info btn-xs" %>
            <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-xs" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path(params: {community_id: @community.id}) %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th>Community</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= blog.user_id %></td>
        <td><%= blog.community_id %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>


<h3><%= link_to @blog.community.title, community_path(@blog.community) %></h3>

<p>
  <h2><%= @blog.title %></h2>
</p>

<p>
  <%= RedCloth.new(@blog.body).to_html.html_safe %>
</p>


<% if signed_in? and @blog.user_id == current_user.id %>
	<%= link_to 'Edit Blog', edit_blog_path(@blog), :class=>"btn btn-info btn-xs" %>
<% end %>

<hr />

<div id="new_comment" class="row">
	<%= render 'comments/form', comment: @comment, blog_id: @blog.id %>
</div>

<div id="comments" class="row">
	<%= render 'comments/index', blog: @blog, comments: @comments %>
</div>

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>">
	<%= RedCloth.new(comment.body).to_html.gsub(/<\/?p>/, '').html_safe %>
  <% if comment.user_id == current_user.id %>
    <br />
    <%= link_to 'Edit', edit_comment_path(comment) %>
    <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(comment, remote: true) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.text_area :body, :class=>"form-control" %>
  </div>

  <%= f.hidden_field :blog_id %>

  <div class="actions">
    <%= f.submit "Reply", :class=>"btn btn-default" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% @comments.each do |comment| %>
  <div id="comment_<%= comment.id %>">
    <%= RedCloth.new(comment.body).to_html.gsub(/<\/?p>/, '').html_safe %>
    <% if comment.user_id == current_user.id %>
      <br />
      <%= link_to 'Edit', edit_comment_path(comment) %>
      <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comments").prepend('<%= j render(@comment) %>')

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.blog_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @comment.blog_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/communities/_form.html.erb
<%= form_for(community) do |f| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :body, 'Description' %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h1>Communities</h1>
</div>

<div class="row">
  <div class="col-md-10">
    <% @communities.each do |community| %>
      <h2><%= link_to community.title, community_path(community) %></h2>
      <%= community.body %><br />
      <% if signed_in? and community.user_id == current_user.id %>
        <%= link_to 'Edit', edit_community_path(community), :class=>"btn btn-info btn-sm" %>
        <%= link_to 'Destroy', community, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-sm" %>
      <% end %>
      <hr />
    <% end %>
  </div>

  <div class="col-md-2">
    <% if signed_in? %>
      <%= link_to 'Create Community', new_community_path, :class=>"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @community.title %>
  <small>/c/<%= @community.url %></small>
</h1>

<p>
  <%= @community.body %>
</p>

<% if signed_in? and @community.user_id == current_user.id %>
	<%= link_to 'Edit', edit_community_path(@community), :class=>"btn btn-info btn-sm" %> |
	<%= link_to 'Back', communities_path, :class=>"btn btn-default btn-sm" %>
<% end %>

<%= render 'blogs/index', blogs: @blogs, community: @community %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Bipplit</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css" crossorigin="anonymous">
    		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>  
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <%= stylesheet_link_tag "application", media: "all" %>
        <%= javascript_include_tag "application" %>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Bipplit", "/", :class=>"navbar-brand" %>
        </div>
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to current_user.email, "#" %>
            </li>
	          <li class="">
	            <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
	          </li>
          <% else %>
	          <li>
	            <%= link_to "Sign In", new_user_session_path %>
	          </li>
	          <li class="">
	            <%= link_to "Sign Up", new_user_registration_path %>
	          </li>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= csrf_meta_tags %>
      <%= yield %>

      <hr>

      <footer>
        <p>&copy; CS 687, 2016 : Martin Cox, Rui Wang</p>
      </footer>
    </div> <!-- /container -->      
    </body>
</html>